name: publish-snapshot

# only trigger a SNAPSHOT release when the build workflow succeeded on main
on:
  workflow_run:
    workflows: [ "build" ]
    types: [ completed ]
    branches: [ "main" ]

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Publish SNAPSHOT
        run: ./mvnw -B --no-transfer-progress deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
